type Query{
  orders: [Order!]!
  myOrders: Orders!
}

type Mutation{
    createOrder(productId:ID!): Order!
    deleteOrder(id:ID!): Order!
    payOrders: response!
}

type response{
  status: Int!
  message: String!
    data: Order
}
type Order {
  id: ID!
  user: User!
  products: Product!
    isPaid: Boolean!
  date: String!
}
type Orders {
  orders: [Order!]!
    total: total!
}

type total{
  paid: Int!
  unpaid: Int!
}
type Product{
    id:ID!
    categoryId: ID!
    name: String!
    price: Int!
    shortDesc: String!
    longDesc: String!
    picture: String!
}
type User{
    id:ID!
    username: String!
    email: String!
    contact: String!
}