type Query {
  totalMonthlySales(paid:Boolean): Float!
    mostSoldProduct(limit:Int!): [soldProduct!]!
    leastSoldProduct(limit:Int!): [soldProduct!]!
}
type soldProduct {
  product: Product!
  count: Int!
}