type Mutation{
    login(input: Login!): AuthResponse!
    register(input: Register!): AuthResponse!
}

type AuthResponse{
    status: Int!
    message: String!
    token: String
}
input Login{
    username: String!
    password: String!
}

input Register{
    username: String!
    password: String!
    repeat_password: String!
    contact:String!,
    email: String!
}

